project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: false
  docx:
    reference-doc: custom-reference-doc.docx
  jats: default
  agu-pdf: default
  
crossref:
  custom:
    - kind: float
      reference-prefix: "Figure S"
      key: supp



